name: Build and release Python packages - Linux
on: workflow_dispatch

jobs:
  build:
    runs-on: ['ubuntu-latest']
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: List available Python versions
        run:
          ls /opt/python
      - name: Install setuptools
        run: |
          /opt/python/cp38-cp38/bin/python -m pip install setuptools
          /opt/python/cp39-cp39/bin/python -m pip install setuptools
          /opt/python/cp310-cp310/bin/python -m pip install setuptools
          /opt/python/cp311-cp311/bin/python -m pip install setuptools
          /opt/python/cp312-cp312/bin/python -m pip install setuptools
          /opt/python/cp313-cp313/bin/python -m pip install setuptools
          /opt/python/cp314-cp314/bin/python -m pip install setuptools
      - name: Build wheels
        run: |
          /opt/python/cp38-cp38/bin/python setup.py bdist_wheel
          /opt/python/cp39-cp39/bin/python setup.py bdist_wheel
          /opt/python/cp310-cp310/bin/python setup.py bdist_wheel
          /opt/python/cp311-cp311/bin/python setup.py bdist_wheel
          /opt/python/cp312-cp312/bin/python setup.py bdist_wheel
          /opt/python/cp313-cp313/bin/python setup.py bdist_wheel
          /opt/python/cp314-cp314/bin/python setup.py bdist_wheel
      - name: Auditwheel & publish
        run: |
          /opt/python/cp39-cp39/bin/pip install auditwheel twine
          auditwheel repair dist/*
          /opt/python/cp39-cp39/bin/python -m twine upload -u __token__  -p ${{ secrets.PYPI_UPLOAD_TOKEN }} wheelhouse/*
