name: Build and release Python packages - MacOS + Windows
on: workflow_dispatch

jobs:
  build:

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [windows-latest, macos-14, macos-15, macos-26]
      fail-fast: false
    runs-on: ${{ matrix.os }}


    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install cmake
        uses: jwlawson/actions-setup-cmake@v1.14
      - name: Build package & upload
        run: | 
          pip install wheel twine setuptools
          python setup.py bdist_wheel
      - name: Publish package
        run:
          twine upload -u __token__  -p ${{ secrets.PYPI_UPLOAD_TOKEN }} dist/*
